// Auto-generated by scripts/fetchKoreanPublicHolidays.mjs.
// Source: Public Data Portal "Korea Astronomy and Space Science Institute - Special Day Information"
// API operation: getHoliDeInfo
// Generated at: 2026-05-15T14:52:06.668Z
// Covered years: 2025-2027
//
// Do not edit the generated holiday rows by hand. Re-run the fetch script when
// the public holiday source range needs to be extended.

export const PUBLIC_HOLIDAY_SOURCE = {
  provider: 'Korea Astronomy and Space Science Institute',
  portal: 'Public Data Portal',
  dataset: '한국천문연구원_특일 정보',
  operation: "getHoliDeInfo",
  generatedAt: "2026-05-15T14:52:06.668Z",
  startYear: 2025,
  years: 3,
};

export const KOREAN_PUBLIC_HOLIDAYS = {
  "2025": [
    {"date":"2025-01-01","title":"1월1일","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2025-01-27","title":"임시공휴일","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2025-01-28","title":"설날","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2025-01-29","title":"설날","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2025-01-30","title":"설날","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2025-03-01","title":"삼일절","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2025-03-03","title":"대체공휴일","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2025-05-05","title":"어린이날 / 부처님오신날","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2025-05-06","title":"대체공휴일","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2025-06-03","title":"임시공휴일(제21대 대통령 선거)","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2025-06-06","title":"현충일","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2025-08-15","title":"광복절","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2025-10-03","title":"개천절","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2025-10-05","title":"추석","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2025-10-06","title":"추석","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2025-10-07","title":"추석","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2025-10-08","title":"대체공휴일","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2025-10-09","title":"한글날","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2025-12-25","title":"기독탄신일","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"}
  ],
  "2026": [
    {"date":"2026-01-01","title":"1월1일","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2026-02-16","title":"설날","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2026-02-17","title":"설날","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2026-02-18","title":"설날","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2026-03-01","title":"삼일절","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2026-03-02","title":"대체공휴일(삼일절)","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2026-05-01","title":"노동절","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2026-05-05","title":"어린이날","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2026-05-24","title":"부처님오신날","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2026-05-25","title":"대체공휴일(부처님오신날)","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2026-06-03","title":"전국동시지방선거","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2026-06-06","title":"현충일","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2026-07-17","title":"제헌절","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2026-08-15","title":"광복절","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2026-08-17","title":"대체공휴일(광복절)","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2026-09-24","title":"추석","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2026-09-25","title":"추석","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2026-09-26","title":"추석","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2026-10-03","title":"개천절","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2026-10-05","title":"대체공휴일(개천절)","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2026-10-09","title":"한글날","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2026-12-25","title":"기독탄신일","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"}
  ],
  "2027": [
    {"date":"2027-01-01","title":"1월1일","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2027-02-06","title":"설날","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2027-02-07","title":"설날","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2027-02-08","title":"설날","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2027-02-09","title":"대체공휴일(설날)","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2027-03-01","title":"삼일절","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2027-05-01","title":"노동절","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2027-05-05","title":"어린이날","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2027-05-13","title":"부처님오신날","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2027-06-06","title":"현충일","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2027-07-17","title":"제헌절","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2027-08-15","title":"광복절","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2027-08-16","title":"대체공휴일(광복절)","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2027-09-14","title":"추석","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2027-09-15","title":"추석","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2027-09-16","title":"추석","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2027-10-03","title":"개천절","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2027-10-04","title":"대체공휴일(개천절)","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2027-10-09","title":"한글날","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2027-10-11","title":"대체공휴일(한글날)","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2027-12-25","title":"기독탄신일","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"},
    {"date":"2027-12-27","title":"대체공휴일(기독탄신일)","holidayType":"publicHoliday","affectsProduction":true,"affectsShipping":true,"shippingClosedFromEnabled":true,"isAutoGenerated":true,"source":"KASI_SPECIAL_DAY_API"}
  ]
};

export function getKoreanPublicHolidaysForYear(year) {
  return [...(KOREAN_PUBLIC_HOLIDAYS[String(year)] || [])];
}

export function getKoreanPublicHolidaysForYears(startYear = PUBLIC_HOLIDAY_SOURCE.startYear, years = PUBLIC_HOLIDAY_SOURCE.years) {
  const result = [];
  for (let year = Number(startYear); year < Number(startYear) + Number(years); year += 1) {
    result.push(...getKoreanPublicHolidaysForYear(year));
  }
  return result;
}
