// KST(Asia/Seoul) 기준 날짜 유틸
// 스펙 18장: 모든 날짜는 Asia/Seoul 기준 YYYY-MM-DD 문자열로 저장

import { db } from '../firebase.js';
import { collection, getDocs } from 'firebase/firestore';
import {
  HOLIDAY_DATA_END_YEAR,
  HOLIDAY_REFRESH_NEEDED_BEFORE,
  getKoreanPublicHolidaysForYears
} from '../services/holidayMaster.js';

const KST_OFFSET_MS = 9 * 60 * 60 * 1000;

// [Phase 7A] holidays 캐시
// 모듈 레벨 변수 — 앱 시작 시 1회 로드, 휴일 등록/삭제 시 갱신
let holidaysCache = [];
let holidayInfoCache = buildStaticHolidayMap();
let holidaysCacheLoaded = false;
let holidayDataExpiryWarned = false;

/**
 * 주어진 Date 객체를 KST 기준 YYYY-MM-DD 문자열로 변환
 * @param {Date} date - 변환할 Date 객체 (기본값: 현재 시각)
 * @returns {string} YYYY-MM-DD
 */
export function formatKstDate(date = new Date()) {
  const kst = new Date(date.getTime() + KST_OFFSET_MS);
  return kst.toISOString().split('T')[0];
}

/**
 * KST 기준 오늘 날짜 (YYYY-MM-DD)
 * 기존 9개 페이지에 흩어져 있던 getToday()의 KST 정정 버전
 */
export function getTodayKST() {
  return formatKstDate(new Date());
}

/**
 * KST 기준 어제 날짜 (YYYY-MM-DD)
 */
export function getYesterdayKST() {
  const now = new Date();
  return formatKstDate(new Date(now.getTime() - 24 * 60 * 60 * 1000));
}

/**
 * 다음 영업일 (토/일 + 휴일 제외, KST 기준)
 *
 * @param {string} dateStr - 기준 날짜 YYYY-MM-DD
 * @param {string[]} holidays - 휴일 배열 (YYYY-MM-DD), 기본 빈 배열
 *                              (Phase 1 V1: 토일만, 추후 holidays 컬렉션 연결 예정)
 * @returns {string} 다음 영업일 YYYY-MM-DD
 */
export function getNextBusinessDay(dateStr, holidays = null) {
  // [Phase 7A] holidays 인자 미전달 시 캐시 자동 사용
  const effectiveHolidays = holidays !== null ? holidays : holidaysCache;
  let cursor = new Date(dateStr + 'T00:00:00+09:00');

  for (let i = 0; i < 365; i++) {
    cursor = new Date(cursor.getTime() + 24 * 60 * 60 * 1000);
    // KST 시간으로 본 요일 = (UTC + 9h)의 UTC 요일
    const kstDay = new Date(cursor.getTime() + KST_OFFSET_MS).getUTCDay();
    const candidate = formatKstDate(cursor);
    warnIfHolidayDataOutOfRange(candidate);

    if (kstDay !== 0 && kstDay !== 6 && !effectiveHolidays.includes(candidate)) {
      return candidate;
    }
  }
  throw new Error('getNextBusinessDay: 365일 초과 — 입력값 확인');
}

function normalizeDateStr(dateStr) {
  if (!dateStr) return '';
  if (dateStr instanceof Date) return formatKstDate(dateStr);
  return String(dateStr).slice(0, 10);
}

function addDaysKST(dateStr, days) {
  const base = new Date(`${normalizeDateStr(dateStr)}T00:00:00+09:00`);
  return formatKstDate(new Date(base.getTime() + days * 24 * 60 * 60 * 1000));
}

function getKstDay(dateStr) {
  const date = new Date(`${normalizeDateStr(dateStr)}T00:00:00+09:00`);
  return new Date(date.getTime() + KST_OFFSET_MS).getUTCDay();
}

function normalizeHolidayDoc(dateStr, data = {}) {
  const date = normalizeDateStr(data.date || dateStr);
  const title = data.title || data.label || data.name || '';
  return {
    id: date,
    date,
    title,
    label: data.label || title,
    description: data.description || data.memo || '',
    holidayType: data.holidayType || (data.isAutoGenerated ? 'publicHoliday' : 'internalOff'),
    affectsProduction: data.affectsProduction === undefined ? true : data.affectsProduction === true,
    affectsShipping: data.affectsShipping === undefined ? true : data.affectsShipping === true,
    shippingClosedFromEnabled: data.shippingClosedFromEnabled === undefined ? true : data.shippingClosedFromEnabled === true,
    isAutoGenerated: data.isAutoGenerated === true,
    recurrenceRule: data.recurrenceRule || null,
    status: data.status || 'active',
    source: data.source || (data.isAutoGenerated ? 'KASI_SPECIAL_DAY_API' : 'firestore'),
  };
}

function buildStaticHolidayMap() {
  const map = {};
  for (const holiday of getKoreanPublicHolidaysForYears()) {
    map[holiday.date] = normalizeHolidayDoc(holiday.date, holiday);
  }
  return map;
}

holidaysCache = Object.keys(holidayInfoCache).sort();

function isWeekend(dateStr) {
  const day = getKstDay(dateStr);
  return day === 0 || day === 6;
}

function isShippingClosed(dateStr) {
  const key = normalizeDateStr(dateStr);
  const day = getKstDay(dateStr);
  if (day === 0) return true;
  const info = getHolidayInfo(key);
  if (info?.affectsShipping === true) return true;
  const prevInfo = getHolidayInfo(addDaysKST(key, -1));
  return prevInfo?.affectsShipping === true && prevInfo.shippingClosedFromEnabled === true;
}

export function getHolidayInfo(dateStr) {
  const key = normalizeDateStr(dateStr);
  const info = holidayInfoCache[key] || null;
  if (!info || info.status === 'deleted') return null;
  return info;
}

export function isHoliday(dateStr) {
  const key = normalizeDateStr(dateStr);
  return isWeekend(key) || getHolidayInfo(key) !== null;
}

export function isBusinessDay(dateStr, type = 'production') {
  const key = normalizeDateStr(dateStr);
  warnIfHolidayDataOutOfRange(key);
  const day = getKstDay(key);
  const info = getHolidayInfo(key);

  if (type === 'shipping') {
    if (day === 0) return false;
    if (info?.affectsShipping === true) return false;
    const prevInfo = getHolidayInfo(addDaysKST(key, -1));
    if (prevInfo?.affectsShipping === true && prevInfo.shippingClosedFromEnabled === true) return false;
    return true;
  }

  if (day === 0 || day === 6) return false;
  if (info?.affectsProduction === true) return false;
  return true;
}

export function addBusinessDays(dateStr, n, type = 'production') {
  if (!Number.isInteger(n)) throw new Error('addBusinessDays: n must be an integer');
  if (n === 0) return normalizeDateStr(dateStr);

  const direction = n > 0 ? 1 : -1;
  let remaining = Math.abs(n);
  let cursor = normalizeDateStr(dateStr);

  for (let i = 0; i < 3650; i++) {
    cursor = addDaysKST(cursor, direction);
    if (isBusinessDay(cursor, type)) remaining -= 1;
    if (remaining === 0) return cursor;
  }
  throw new Error('addBusinessDays: 3650일 초과 — 입력값 확인');
}

export function getNextBusinessDayByType(dateStr, type = 'production') {
  return addBusinessDays(dateStr, 1, type);
}

export function isLongShippingHoliday(dateStr) {
  const key = normalizeDateStr(dateStr);
  if (!isShippingClosed(key)) return false;

  let start = key;
  while (isShippingClosed(addDaysKST(start, -1))) start = addDaysKST(start, -1);

  let hasAffectingHoliday = false;
  let count = 0;
  let cursor = start;
  for (let i = 0; i < 30 && isShippingClosed(cursor); i++) {
    count += 1;
    if (getHolidayInfo(cursor)?.affectsShipping === true) hasAffectingHoliday = true;
    cursor = addDaysKST(cursor, 1);
  }

  return hasAffectingHoliday && count >= 2;
}

function warnIfHolidayDataOutOfRange(dateStr) {
  if (holidayDataExpiryWarned) return;
  if (!isHolidayDataOutOfRange(dateStr)) return;
  holidayDataExpiryWarned = true;
  console.warn(`[holiday] Korean public holiday data only covers through ${HOLIDAY_DATA_END_YEAR}. Refresh required before using ${dateStr}.`);
}

export function isHolidayDataOutOfRange(dateStr) {
  if (!dateStr || !HOLIDAY_DATA_END_YEAR) return false;
  const year = Number(String(dateStr).slice(0, 4));
  return Number.isFinite(year) && year > HOLIDAY_DATA_END_YEAR;
}

export function getHolidayDataNotice(referenceDateStr = getTodayKST()) {
  if (!HOLIDAY_DATA_END_YEAR || !HOLIDAY_REFRESH_NEEDED_BEFORE) return null;

  if (isHolidayDataOutOfRange(referenceDateStr)) {
    return {
      level: 'expired',
      message: `한국 공휴일 데이터가 ${HOLIDAY_DATA_END_YEAR}년까지만 등록되어 있습니다. 공휴일 데이터를 갱신해야 영업일 계산이 정확합니다.`,
    };
  }

  if (referenceDateStr >= HOLIDAY_REFRESH_NEEDED_BEFORE) {
    return {
      level: 'warning',
      message: `한국 공휴일 데이터가 ${HOLIDAY_DATA_END_YEAR}년 말까지입니다. ${HOLIDAY_REFRESH_NEEDED_BEFORE} 이후에는 다음 연도 데이터 갱신을 준비해주세요.`,
    };
  }

  return null;
}
/**
 * KST 기준 N개월 후 날짜 (YYYY-MM-DD)
 * 동결제품 유통기한(18개월 후) 등에 사용. toISOString()의 UTC 기준 버그 회피용.
 *
 * @param {number} months - 더할 개월 수 (음수도 가능)
 * @param {Date} baseDate - 기준 시각 (기본값: 현재)
 * @returns {string} YYYY-MM-DD
 */
export function addMonthsKST(months, baseDate = new Date()) {
  // KST 기준의 연/월/일을 추출
  const kst = new Date(baseDate.getTime() + KST_OFFSET_MS);
  const y = kst.getUTCFullYear();
  const m = kst.getUTCMonth();
  const d = kst.getUTCDate();
  // KST 기준 (y, m+months, d) 만들고 다시 KST YYYY-MM-DD로 포맷
  const target = new Date(Date.UTC(y, m + months, d));
  return formatKstDate(new Date(target.getTime() - KST_OFFSET_MS));
}
/**
 * 두 날짜의 일수 차이 (KST 기준)
 * @returns {number} dateAStr - dateBStr (양수면 A가 더 미래)
 */
export function diffDaysKST(dateAStr, dateBStr) {
  const a = new Date(dateAStr + 'T00:00:00+09:00');
  const b = new Date(dateBStr + 'T00:00:00+09:00');
  return Math.round((a - b) / (24 * 60 * 60 * 1000));
}

/**
 * [Phase 3b 신규]
 * KST 기준 'M/D(요일)' 형식 변환 (배너/모달 표시용).
 * 예: '2026-04-28' -> '4/28(화)'
 *
 * 월/일은 입력 문자열을 그대로 파싱해서 환경 시간대 무관.
 * 요일은 KST 정오를 anchor로 계산해 자정 경계 이슈 회피.
 *
 * @param {string} dateStr - 'YYYY-MM-DD'
 * @returns {string} 'M/D(요일)' 또는 빈 문자열(입력이 falsy일 때)
 */
export function formatKstDateWithDay(dateStr) {
  if (!dateStr) return '';
  const parts = dateStr.split('-');
  if (parts.length !== 3) return '';
  const month = parseInt(parts[1], 10);
  const day = parseInt(parts[2], 10);
  if (Number.isNaN(month) || Number.isNaN(day)) return '';

  const days = ['일', '월', '화', '수', '목', '금', '토'];
  const kstNoon = new Date(dateStr + 'T12:00:00+09:00');
  const kstDayIdx = new Date(kstNoon.getTime() + KST_OFFSET_MS).getUTCDay();

  return `${month}/${day}(${days[kstDayIdx]})`;
}
/**
 * [Phase 7A]
 * holidays 컬렉션 전체를 fetch해서 캐시에 저장.
 * 앱 시작 시 1회 호출 + 휴일 등록/삭제 시 호출.
 *
 * @returns {Promise<string[]>} 캐시된 휴일 배열 (YYYY-MM-DD)
 */
export async function loadHolidaysCache() {
  const snap = await getDocs(collection(db, 'holidays'));
  const merged = buildStaticHolidayMap();
  snap.docs.forEach(d => {
    const normalized = normalizeHolidayDoc(d.id, d.data());
    if (normalized.status === 'deleted') {
      delete merged[normalized.date];
    } else {
      merged[normalized.date] = normalized;
    }
  });

  holidayInfoCache = merged;
  holidaysCache = Object.keys(merged).sort();
  holidaysCacheLoaded = true;
  return holidaysCache;
}

/**
 * [Phase 7A]
 * 현재 캐시된 휴일 배열을 반환. 캐시 미로드면 빈 배열.
 *
 * @returns {string[]}
 */
export function getHolidaysCache() {
  return holidaysCache;
}

export function getHolidayInfoCache() {
  return { ...holidayInfoCache };
}

/**
 * [Phase 7A]
 * 캐시 로드 여부 확인.
 *
 * @returns {boolean}
 */
export function isHolidaysCacheLoaded() {
  return holidaysCacheLoaded;
}
