#!/usr/bin/env node

import fs from 'node:fs/promises';
import path from 'node:path';

const API_BASE = 'https://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService';
const DEFAULT_OPERATION = 'getHoliDeInfo';
const DEFAULT_OUT = 'src/services/holidayMaster.js';

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (!arg.startsWith('--')) continue;
    const key = arg.slice(2);
    const next = argv[i + 1];
    if (!next || next.startsWith('--')) {
      args[key] = true;
    } else {
      args[key] = next;
      i += 1;
    }
  }
  return args;
}

function usage() {
  return `
Usage:
  npm run fetch:holidays -- --service-key "DATA_GO_KR_KEY"

Options:
  --service-key <key>       Public Data Portal service key. Or set DATA_GO_KR_SERVICE_KEY.
  --start-year <year>       First year to fetch. Default: current KST year.
  --years <count>           Number of years to fetch. Default: 5.
  --operation <name>        API operation. Default: ${DEFAULT_OPERATION}.
  --out <path>              Output file. Default: ${DEFAULT_OUT}.
  --delay-ms <ms>           Delay between yearly calls. Default: 1200.
  --dry-run                 Print parsed holidays without writing a file.
`;
}

function getCurrentKstYear() {
  const now = new Date();
  const kst = new Date(now.getTime() + 9 * 60 * 60 * 1000);
  return kst.getUTCFullYear();
}

function encodeServiceKey(key) {
  // data.go.kr displays both encoded and decoded keys. If the user passes an
  // already-encoded key, keep it as-is to avoid double encoding.
  return /%[0-9a-f]{2}/i.test(key) ? key : encodeURIComponent(key);
}

function normalizeItems(items) {
  if (!items) return [];
  if (Array.isArray(items)) return items;
  return [items];
}

function getNested(obj, pathParts) {
  let cursor = obj;
  for (const part of pathParts) {
    if (cursor == null) return undefined;
    cursor = cursor[part];
  }
  return cursor;
}

function parseJsonPayload(text) {
  const data = JSON.parse(text);
  const resultCode = getNested(data, ['response', 'header', 'resultCode']);
  if (resultCode && resultCode !== '00') {
    const resultMsg = getNested(data, ['response', 'header', 'resultMsg']) || 'unknown error';
    throw new Error(`API resultCode=${resultCode}: ${resultMsg}`);
  }

  const rawItems = getNested(data, ['response', 'body', 'items', 'item']);
  return normalizeItems(rawItems);
}

function extractXmlTag(xml, tag) {
  const match = xml.match(new RegExp(`<${tag}>([\\s\\S]*?)<\\/${tag}>`));
  return match ? decodeXml(match[1].trim()) : '';
}

function decodeXml(value) {
  return value
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&amp;/g, '&')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");
}

function parseXmlPayload(text) {
  const resultCode = extractXmlTag(text, 'resultCode');
  if (resultCode && resultCode !== '00') {
    const resultMsg = extractXmlTag(text, 'resultMsg') || 'unknown error';
    throw new Error(`API resultCode=${resultCode}: ${resultMsg}`);
  }

  const itemMatches = text.matchAll(/<item>([\s\S]*?)<\/item>/g);
  return Array.from(itemMatches, m => ({
    dateKind: extractXmlTag(m[1], 'dateKind'),
    dateName: extractXmlTag(m[1], 'dateName'),
    isHoliday: extractXmlTag(m[1], 'isHoliday'),
    locdate: extractXmlTag(m[1], 'locdate'),
    seq: extractXmlTag(m[1], 'seq'),
  }));
}

function parsePayload(text) {
  try {
    return parseJsonPayload(text);
  } catch (jsonErr) {
    if (!text.includes('<response') && !text.includes('<OpenAPI_ServiceResponse')) {
      throw jsonErr;
    }
    return parseXmlPayload(text);
  }
}

function formatLocdate(locdate) {
  const raw = String(locdate || '').replace(/\D/g, '');
  if (!/^\d{8}$/.test(raw)) return '';
  return `${raw.slice(0, 4)}-${raw.slice(4, 6)}-${raw.slice(6, 8)}`;
}

function normalizeHolidayItem(item) {
  const date = formatLocdate(item.locdate);
  const title = String(item.dateName || '').trim();
  const isHoliday = String(item.isHoliday || '').trim().toUpperCase() === 'Y';
  if (!date || !title || !isHoliday) return null;

  return {
    date,
    title,
    holidayType: 'publicHoliday',
    affectsProduction: true,
    affectsShipping: true,
    shippingClosedFromEnabled: true,
    isAutoGenerated: true,
    source: 'KASI_SPECIAL_DAY_API',
  };
}

async function fetchYear({ serviceKey, year, operation }) {
  const query = [
    `ServiceKey=${encodeServiceKey(serviceKey)}`,
    'pageNo=1',
    'numOfRows=100',
    `solYear=${year}`,
    '_type=json',
  ].join('&');
  const url = `${API_BASE}/${operation}?${query}`;

  const res = await fetch(url);
  const text = await res.text();
  if (!res.ok) {
    const err = new Error(`HTTP ${res.status} for ${year}: ${text.slice(0, 200)}`);
    err.status = res.status;
    throw err;
  }

  return parsePayload(text)
    .map(normalizeHolidayItem)
    .filter(Boolean)
    .sort((a, b) => a.date.localeCompare(b.date));
}

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function fetchYearWithRetry(options) {
  const maxAttempts = 3;
  for (let attempt = 1; attempt <= maxAttempts; attempt += 1) {
    try {
      return await fetchYear(options);
    } catch (err) {
      const retryable = err.status === 401 || err.status === 429 || err.status >= 500;
      if (!retryable || attempt === maxAttempts) throw err;
      const waitMs = 1500 * attempt;
      console.warn(`[holidays] ${options.year}: ${err.message}; retrying in ${waitMs}ms`);
      await sleep(waitMs);
    }
  }
  return [];
}

function groupByYear(holidays) {
  const grouped = {};
  for (const holiday of holidays) {
    const year = holiday.date.slice(0, 4);
    if (!grouped[year]) grouped[year] = [];
    grouped[year].push(holiday);
  }
  return grouped;
}

function dedupeByDate(holidays) {
  const byDate = new Map();
  for (const holiday of holidays) {
    const existing = byDate.get(holiday.date);
    if (!existing) {
      byDate.set(holiday.date, { ...holiday });
      continue;
    }

    const titles = new Set([
      ...String(existing.title || '').split(' / ').filter(Boolean),
      holiday.title,
    ]);
    existing.title = Array.from(titles).join(' / ');
  }
  return Array.from(byDate.values()).sort((a, b) => a.date.localeCompare(b.date));
}

function jsString(value) {
  return JSON.stringify(value);
}

function renderHolidayMaster({ grouped, startYear, years, operation }) {
  const generatedAt = new Date().toISOString();
  const dataLines = Object.entries(grouped)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([year, items]) => {
      const rows = items.map(item => `    ${JSON.stringify(item)}`).join(',\n');
      return `  ${jsString(year)}: [\n${rows}\n  ]`;
    })
    .join(',\n');

  return `// Auto-generated by scripts/fetchKoreanPublicHolidays.mjs.
// Source: Public Data Portal "Korea Astronomy and Space Science Institute - Special Day Information"
// API operation: ${operation}
// Generated at: ${generatedAt}
// Covered years: ${startYear}-${startYear + years - 1}
//
// Do not edit the generated holiday rows by hand. Re-run the fetch script when
// the public holiday source range needs to be extended.

export const PUBLIC_HOLIDAY_SOURCE = {
  provider: 'Korea Astronomy and Space Science Institute',
  portal: 'Public Data Portal',
  dataset: '한국천문연구원_특일 정보',
  operation: ${jsString(operation)},
  generatedAt: ${jsString(generatedAt)},
  startYear: ${startYear},
  years: ${years},
};

export const KOREAN_PUBLIC_HOLIDAYS = {
${dataLines}
};

export function getKoreanPublicHolidaysForYear(year) {
  return [...(KOREAN_PUBLIC_HOLIDAYS[String(year)] || [])];
}

export function getKoreanPublicHolidaysForYears(startYear = PUBLIC_HOLIDAY_SOURCE.startYear, years = PUBLIC_HOLIDAY_SOURCE.years) {
  const result = [];
  for (let year = Number(startYear); year < Number(startYear) + Number(years); year += 1) {
    result.push(...getKoreanPublicHolidaysForYear(year));
  }
  return result;
}
`;
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.help) {
    console.log(usage());
    return;
  }

  const serviceKey = args['service-key'] ||
    process.env.DATA_GO_KR_SERVICE_KEY ||
    process.env.PUBLIC_DATA_SERVICE_KEY;
  if (!serviceKey) {
    throw new Error(`Missing service key.${usage()}`);
  }

  const startYear = Number(args['start-year'] || getCurrentKstYear());
  const years = Number(args.years || 5);
  const operation = String(args.operation || DEFAULT_OPERATION);
  const out = String(args.out || DEFAULT_OUT);
  const delayMs = Number(args['delay-ms'] || 1200);

  if (!Number.isInteger(startYear) || startYear < 2000) {
    throw new Error(`Invalid --start-year: ${args['start-year']}`);
  }
  if (!Number.isInteger(years) || years < 1 || years > 20) {
    throw new Error(`Invalid --years: ${args.years}`);
  }

  const all = [];
  for (let offset = 0; offset < years; offset += 1) {
    const year = startYear + offset;
    console.log(`[holidays] fetching ${year} (${operation})`);
    const yearItems = dedupeByDate(await fetchYearWithRetry({ serviceKey, year, operation }));
    console.log(`[holidays] ${year}: ${yearItems.length} holidays`);
    all.push(...yearItems);
    if (offset < years - 1 && delayMs > 0) {
      await sleep(delayMs);
    }
  }

  const grouped = groupByYear(all);
  const source = renderHolidayMaster({ grouped, startYear, years, operation });

  if (args['dry-run']) {
    console.log(JSON.stringify(grouped, null, 2));
    return;
  }

  await fs.mkdir(path.dirname(out), { recursive: true });
  await fs.writeFile(out, source, 'utf8');
  console.log(`[holidays] wrote ${out}`);
}

main().catch(err => {
  console.error(`[holidays] ${err.message}`);
  process.exit(1);
});
